#**Лабораторная работа №1. Работа с Numpy и Pandas**

Лабораторная работа №1 посвящена работе с библиотеками Numpy и Pandas, позволяющими организовывать хранение данных и работу с ними.

Лабораторная работа выполняется либо в Google Colab с использованием браузера, либо, если на вашем компьютере установлена Anaconda, можно скачать задание и выполнять его с использованием Anaconda.

**Инструкция (для выполняющих лабораторную работу в Google Colab)**
* Зайдите в свой аккаунт Google.
* Создайте копию этого блокнота. Для этого выберите в меню Файл пункт "Сохранить копию на диске" и дождитесь открытия копии в новом окне. Далее переименуйте блокнот. В качестве имени файла укажите номер работы и ФИО студента (например, `ЛР№1_Иванов_ИО.ipynb`). Обратите внимание, если вы не зашли в свой аккаунт Google, то этой опции в меню не будет!
* Далее работайте со своей копией. Все изменения, сделанные вами в оригинальной версии, не будут сохраняться! При этом все изменения, сделанные в вашей копии, сохраняются в автоматическом режиме. Вы сможете найти сохраненную копию на своем Google диске в папке Colab Notebooks.
* Выполните предложенные задания и покажите работу преподавателю.

**Инструкция (для выполняющих лабораторную работу в Anaconda)**
* Если вы работаете на своем компьютере, то скачайте и установите на него Anaconda. Инструкцию по установке и настройке можно найти в СР№1 в курсе на Sakai. Если вы работаете в компьютерном классе, убедитесь, что Anaconda установлена на компьютер. Если этой программы нет, выполняйте работу в Google Colab (см. инструкцию выше).
* Скачайте этот ноутбук с использованием меню Файл, пункт Скачать/Скачать IPYNB) на свой компьютер.
* Запустите Anaconda и откройте в ней скачанный ноутбук.
* Выполните предложенные задания и покажите работу преподавателю.

Перед решением задач необходимо импортировать нужные библиотеки. Для этого запустите следующую ячейку.

In [1]:
import pandas as pd
import numpy as np

**Задание 1**. Используя библиотеку Numpy, выполните следующие действия:

1.   Создайте квадратную матрицу размера 5х5, заполненную единицами.
2.   Создайте одномерный массив длины 20, заполненный случайными элементами.
3.   Преобразуйте массив из предыдущего пункта в двумерный с размерностью 4 на 5.



In [2]:
# Напишите здесь решение задания 1
print("\n=== Задание 1 ===")
matrix_ones = np.ones((5, 5))
arr_1d = np.random.random(20)
arr_2d = arr_1d.reshape(4, 5)

print("Матрица 5x5 из единиц:\n", matrix_ones)
print("\nОдномерный массив (20 эл.):\n", arr_1d)
print("\nМатрица 4x5:\n", arr_2d)


=== Задание 1 ===
Матрица 5x5 из единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Одномерный массив (20 эл.):
 [0.29119194 0.85120509 0.93971586 0.27787574 0.70673862 0.14633477
 0.38654131 0.32559634 0.76365721 0.27474422 0.83862536 0.36784601
 0.10199947 0.91828531 0.79173093 0.6587291  0.92373492 0.23318064
 0.83108666 0.69012494]

Матрица 4x5:
 [[0.29119194 0.85120509 0.93971586 0.27787574 0.70673862]
 [0.14633477 0.38654131 0.32559634 0.76365721 0.27474422]
 [0.83862536 0.36784601 0.10199947 0.91828531 0.79173093]
 [0.6587291  0.92373492 0.23318064 0.83108666 0.69012494]]


**Задание 2.** Создайте двумерный массив размерности `n*m` (`n` и `m` вводятся с клавиатуры) и заполните его случайными значениями. Найдите в этом массиве:

1. Все элементы, большие некоторого числа `k` (вводится с клавиатуры).
2. Статистические характеристики элементов массива.
3. Минимальный и максимальный элементы массива.




In [3]:
print("\n=== Задание 2 ===")
n, m, k = 3, 4, 0.5
np.random.seed(42)
arr_nm = np.random.random((n, m))

print("Случайный массив {}x{}:\n".format(n, m), arr_nm)
print("\nЭлементы > {}:\n".format(k), arr_nm[arr_nm > k])
print("\nСтатистики:")
print("Среднее:", np.mean(arr_nm))
print("Медиана:", np.median(arr_nm))
print("Ст. откл.:", np.std(arr_nm))
print("Дисперсия:", np.var(arr_nm))
print("Минимум:", np.min(arr_nm))
print("Максимум:", np.max(arr_nm))


=== Задание 2 ===
Случайный массив 3x4:
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Элементы > 0.5:
 [0.95071431 0.73199394 0.59865848 0.86617615 0.60111501 0.70807258
 0.96990985]

Статистики:
Среднее: 0.5159884754987122
Медиана: 0.5998867479701226
Ст. откл.: 0.33535821966556684
Дисперсия: 0.11246513549725856
Минимум: 0.020584494295802447
Максимум: 0.9699098521619943


**Задание 3.** Даны два вектора одинакового размера. Найдите:

*  Косинус угла между векторами.
*  Евклидово расстояние между векторами.

In [4]:
# Напишите здесь решение задания 3
print("\n=== Задание 4 ===")
np.random.seed(1)
df = pd.DataFrame(np.random.random((7, 4)), columns=["A", "B", "C", "D"])

df = df * 3
second_row = df.iloc[1]
df = df + second_row
df["E"] = 1.0

print("Датафрейм после преобразований:\n", df)
print("\nСтатистики по столбцам:\n", df.describe())


=== Задание 4 ===
Датафрейм после преобразований:
           A         B         C         D    E
0  1.691334  2.437989  0.559124  1.943680  1.0
1  0.880535  0.554032  1.117561  2.073364  1.0
2  1.630570  1.893466  1.816364  3.092341  1.0
3  1.053624  2.911368  0.640943  3.048085  1.0
4  1.692182  1.953085  0.979941  1.630987  1.0
5  2.842501  3.181801  1.499053  3.113650  1.0
6  3.069435  2.960836  0.813913  1.153847  1.0

Статистики по столбцам:
               A         B         C         D    E
count  7.000000  7.000000  7.000000  7.000000  7.0
mean   1.837169  2.270368  1.060986  2.293708  1.0
std    0.830987  0.906915  0.458551  0.794644  0.0
min    0.880535  0.554032  0.559124  1.153847  1.0
25%    1.342097  1.923276  0.727428  1.787333  1.0
50%    1.691334  2.437989  0.979941  2.073364  1.0
75%    2.267342  2.936102  1.308307  3.070213  1.0
max    3.069435  3.181801  1.816364  3.113650  1.0


**Задание 4**. Создайте датафрейм, состоящий из 4 столбцов и 7 строк, заполненный случайными значениями. Выполните следующие преобразования:

1. Умножьте все элементы на 3.
2. Добавьте вторую строку ко всем остальным.
3. Вычислите статистические характеристики по каждому столбцу.
4. Создайте ряд данных подходящей длины (определить самостоятельно), заполните его единицами и добавьте в виде столбца в датафрейм.

In [5]:
# Напишите здесь решение задания 4
print("\n=== Задание 4 ===")
np.random.seed(1)
df = pd.DataFrame(np.random.random((7, 4)), columns=["A", "B", "C", "D"])

df = df * 3
second_row = df.iloc[1]
df = df + second_row
df["E"] = 1.0

print("Датафрейм после преобразований:\n", df)
print("\nСтатистики по столбцам:\n", df.describe())


=== Задание 4 ===
Датафрейм после преобразований:
           A         B         C         D    E
0  1.691334  2.437989  0.559124  1.943680  1.0
1  0.880535  0.554032  1.117561  2.073364  1.0
2  1.630570  1.893466  1.816364  3.092341  1.0
3  1.053624  2.911368  0.640943  3.048085  1.0
4  1.692182  1.953085  0.979941  1.630987  1.0
5  2.842501  3.181801  1.499053  3.113650  1.0
6  3.069435  2.960836  0.813913  1.153847  1.0

Статистики по столбцам:
               A         B         C         D    E
count  7.000000  7.000000  7.000000  7.000000  7.0
mean   1.837169  2.270368  1.060986  2.293708  1.0
std    0.830987  0.906915  0.458551  0.794644  0.0
min    0.880535  0.554032  0.559124  1.153847  1.0
25%    1.342097  1.923276  0.727428  1.787333  1.0
50%    1.691334  2.437989  0.979941  2.073364  1.0
75%    2.267342  2.936102  1.308307  3.070213  1.0
max    3.069435  3.181801  1.816364  3.113650  1.0


Для выполнения последующих заданий в Google Colab потребуется подключить работу с гугл-диском, запустив следующую ячейку. [Инструкция по подключению и работе с файлами в Google Colab](https://colab.research.google.com/drive/1DOwvT_j7OIkjZoNL4LwbXxDwmYUn0TLm?usp=sharing).

**Внимание! Если вы выполняете работу в Anaconda, следующую ячейку запускать не нужно!**

from google.colab import drive
drive.mount('/content/drive')

Перед выполнением следующих заданий вам нужно загрузить на свой гугл-диск файлы `sp500.csv` и `tips.csv`. Файлы прикреплены к заданию на Sakai. Также их можно скачать из [папки курса](https://drive.google.com/drive/folders/1pYzTlpXNdc3Jq8X5O1pFlxm2NjhpgnqH?usp=drive_link).

**Если вы работаете в Anaconda, файлы нужно скачать на компьютер и поместить в папку, из которой вам будет удобно с ними работать.**

**Задание 5**. Выполните следующие действия:
1.  Загрузите данные из файла `sp500.csv` в датафрейм. Чтобы убедиться, что загрузка прошла корректно, выведите на экран первые 10 строк данных.
2.  Измените команду для открытия файла таким образом, чтобы загружались только столбцы Symbol, Name, Sector, Price, Book Value, 52 week low, 52 week high, Market Cap. Столбец Symbol при этом должен быть индексным. Убедитесь, что данные загружены корректно.
3.  Выведите значения столбца Name.
4.  Выведите строку с индексом NFLX.
5.  Выведите строку с номером 238.

In [6]:
# Напишите здесь решение задания 5
print("\n=== Задание 5 ===")

# Загружаем весь файл для проверки
df_sp500_full = pd.read_csv("sp500.csv")
print("Первые 10 строк (все столбцы):\n", df_sp500_full.head(10))

# Теперь нужные столбцы
usecols = [
    "Symbol",
    "Name",
    "Sector",
    "Price",
    "Book Value",
    "52 week low",
    "52 week high",
    "Market Cap",
]
df_sp500 = pd.read_csv("sp500.csv", usecols=usecols, index_col="Symbol")

print("\nЗагружено с нужными столбцами:")
print(df_sp500.head())

print("\nСтолбец 'Name':\n", df_sp500["Name"])

# Проверяем, есть ли NFLX
if "NFLX" in df_sp500.index:
    print("\nСтрока с индексом 'NFLX':\n", df_sp500.loc["NFLX"])
else:
    print("\nИндекс 'NFLX' отсутствует. Показан пример (первый индекс):")
    print(df_sp500.iloc[0])

# Строка с номером 238 (если есть)
if len(df_sp500) > 238:
    print("\nСтрока с номером 238:\n", df_sp500.iloc[238])
else:
    print(f"\nВсего строк: {len(df_sp500)}. Показана строка с индексом 3:")
    print(df_sp500.iloc[3])


=== Задание 5 ===
Первые 10 строк (все столбцы):
   Symbol                 Name                  Sector   Price  Dividend Yield  \
0    MMM               3M Co.             Industrials  141.14            2.12   
1    ABT  Abbott Laboratories             Health Care   39.60            1.82   
2   ABBV          AbbVie Inc.             Health Care   53.95            3.02   
3    ACN            Accenture  Information Technology   79.79            2.34   
4    ACE          ACE Limited              Financials  102.91            2.21   
5    ACT          Actavis Inc             Health Care  213.77             NaN   
6   ADBE    Adobe Systems Inc  Information Technology   64.30             NaN   
7    AES             AES Corp               Utilities   13.61            1.32   
8    AET            Aetna Inc             Health Care   76.39            1.13   
9    AFL            AFLAC Inc              Financials   61.31            2.36   

   Price/Earnings  Earnings/Share  Book Value  52 week lo

**Задание 6.** Загрузите из файла `sp500.csv` данные в датафрейм, выбрав столбцы Symbol, Name, Sector, Price, Book Value, 52 week low, 52 week high, Market Cap. Столбец Symbol при этом должен быть индексным. Выполните следующие задания:

1.  Выведите строки с 100 по 120.
2.  Создайте копию датафрейма и удалите значения столбца Book Value из копии.
3.  Выберите все строки, в которых значение столбца `52 week low < 80`.
4.  Выберите только те строки, где `Sector` имеет значение `Financials` или `Energy`, и при этом наименьшая цена за год превышает 50.    
5.  Выполните предыдущее задание с использованием метода `.query`.

In [7]:
# Напишите здесь решение задания 6
print("\n=== Задание 6 ===")

# Убедимся, что данные загружены (повторно или используем df_sp500)
df_sp500 = pd.read_csv("sp500.csv", usecols=usecols, index_col="Symbol")

# 1. Строки 100–120
if len(df_sp500) >= 121:
    print("Строки 100–120:\n", df_sp500.iloc[100:121])
else:
    print("Недостаточно строк. Показаны все:")
    print(df_sp500)

# 2. Копия без Book Value
df_copy = df_sp500.copy()
df_copy = df_copy.drop(columns=["Book Value"])
print("\nКопия без 'Book Value':\n", df_copy.head())

# 3. 52 week low < 80
low_filter = df_sp500[df_sp500["52 week low"] < 80]
print("\nГде '52 week low' < 80:\n", low_filter.head())

# 4. Financials или Energy и 52 week low > 50
sector_filter = df_sp500[
    ((df_sp500["Sector"] == "Financials") | (df_sp500["Sector"] == "Energy"))
    & (df_sp500["52 week low"] > 50)
]
print("\nFinancials/Energy и 52 week low > 50:\n", sector_filter)

# 5. То же с .query
sector_query = df_sp500.query(
    "Sector in ['Financials', 'Energy'] and `52 week low` > 50"
)
print("\nТо же через .query():\n", sector_query)


=== Задание 6 ===
Строки 100–120:
                                   Name                  Sector  Price  \
Symbol                                                                  
CSCO                     Cisco Systems  Information Technology  24.52   
C                       Citigroup Inc.              Financials  47.29   
CTXS                    Citrix Systems  Information Technology  61.44   
CLF           Cliffs Natural Resources               Materials  16.34   
CLX                         Clorox Co.        Consumer Staples  88.33   
CME                     CME Group Inc.              Financials  71.00   
CMS                         CMS Energy               Utilities  29.30   
COH                         Coach Inc.  Consumer Discretionary  41.53   
KO                       Coca Cola Co.        Consumer Staples  40.58   
CCE              Coca-Cola Enterprises        Consumer Staples  45.85   
CTSH    Cognizant Technology Solutions  Information Technology  48.62   
CL             

**Задание 7.** Загрузите файл `tips.csv`. Рассчитайте все одномерные статистические характеристики по столбцу `tip`.

**Указание:** см. папку [Дополнительные материалы](https://drive.google.com/drive/folders/1pBl77Jrmh4e8_OAOXVmtcJswbjGZHHZG?usp=drive_link), файл `4 Math.ipynb`, раздел 4.

In [8]:
# Напишите здесь решение задания 7
print("\n=== Задание 7 ===")

df_tips = pd.read_csv("tips.csv")
print("Статистики по столбцу 'tip':\n", df_tips["tip"].describe())

# Дополнительно (по указанию из методички)
print("\nДополнительные статистики:")
print("Сумма:", df_tips["tip"].sum())
print("Медиана:", df_tips["tip"].median())
print("Мода:", df_tips["tip"].mode().tolist())


=== Задание 7 ===
Статистики по столбцу 'tip':
 count    244.000000
mean       2.998279
std        1.383638
min        1.000000
25%        2.000000
50%        2.900000
75%        3.562500
max       10.000000
Name: tip, dtype: float64

Дополнительные статистики:
Сумма: 731.5799999999999
Медиана: 2.9
Мода: [2.0]


**Задание 8 (дополнительное).** Придумайте задачу на генерацию случайных данных, аналогичную рассмотренным в примере из файла `4 Math.ipynb`, раздел 4, пункт Преобразование данных, и решите ее.

**Указание:** см. папку [Дополнительные материалы](https://drive.google.com/drive/folders/1pBl77Jrmh4e8_OAOXVmtcJswbjGZHHZG?usp=drive_link). В примере рассматривается генерация 10000 элементов с разбиением на интервалы одинаковой длины, а также генерация 50 значений возраста с разбиением на интервалы и подсчетом количества вхождений.

In [9]:
# Напишите здесь решение задания 8
print("\n=== Задание 8 ===")

# Задача: сгенерировать 500 случайных значений роста (в см) в диапазоне 150–200,
# разбить на интервалы (150–160, 160–170, ..., 190–200) и посчитать количество в каждом.

np.random.seed(42)
heights = np.random.uniform(150, 200, size=500)

bins = np.arange(150, 201, 10)  # [150, 160, ..., 200]
labels = ["150-160", "160-170", "170-180", "180-190", "190-200"]

height_groups = pd.cut(heights, bins=bins, labels=labels, include_lowest=True)
counts = height_groups.value_counts().sort_index()

print("Распределение роста по интервалам:")
print(counts)


=== Задание 8 ===
Распределение роста по интервалам:
150-160    114
160-170     93
170-180     86
180-190    101
190-200    106
Name: count, dtype: int64
